name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Build Package
      run: |
        swift build

    - name: Run Tests
      run: |
        swift test

    - name: Run SwiftLint
      run: |
        brew install swiftlint
        swiftlint